language: python

python:
  - "3.5"

notifications:
  email: false
  
sudo: false
cache: pip

addons:
  postgresql: "9.6"
  apt:
    packages:
      - expect-dev
      - python-lxml
      
env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true
  
before_install:
  - pip install codecov coverage

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
- codecov -f coverage.xml
